name: BIDS-Terms viwer via GitHub Pages

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/master'
        with:
          ACCESS_TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}
          BRANCH: gh-pages 
          FOLDER: build
