## This workflow runs term_use_freq.py to generate concepts markdown table

name: Generate Concepts Markdown Table
on:
  push:
    branches: [ master ]
  pull_request:
    branches: '*'
    
jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install packages
      run: |
        python -m pip install --upgrade pip setuptools
        pip install glob2 pyld argparse 
        
    - name: Create md table
      run: |
        python utils/term_use_freq.py -jsonld terms/OpenNeuro_Datasets_Terms/OpenNeuro_jsonld/ -outfile terms/concept_freq.md
        
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: pre-commit/action@v2.0.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
